development:
  adapter: postgresql
  encoding: unicode
  database: jonathanschack
  pool: 5
  username: jonathanschack
  password: jonathanschack
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: jonathanschack
  pool: 5
  username: jonathanschack
  password: jonathanschack
  timeout: 5000